# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - 6sp-api

on:
  push:
    branches:
      - ci-cd
    paths: ./backend/app/
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      
      - name: create env file
        run: |
          touch .env
          echo MONGODB_URI=${{ secrets.MONGODB_URI }} >> .env
          echo ACCESS_SECRET=${{ secrets.ACCESS_SECRET }} >> .env
          echo REFRESH_SECRET=${{ secrets.REFRESH_SECRET }} >> .env
          echo ACCESS_TIME=${{ secrets.ACCESS_TIME }} >> .env
          echo REFRESH_TIME=${{ secrets.REFRESH_TIME }} >> .env
          echo PORT=${{ secrets.PORT }} >> .env

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
        working-directory: ./backend/app/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path:  ./backend/app/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: '6sp-api'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_023043CE085E4F4F9966DE00D8865990 }}
          package: .
